name: Deploy-Functiongraph

on:
  push:
    branches: 
    - 'main'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 推送通知配置
      PUSH_METHOD: ${{ secrets.PUSH_METHOD }}
      PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      WXPUSHER_SPT: ${{ secrets.WXPUSHER_SPT }}
      VERCEL_API_URL: ${{ secrets.VERCEL_API_URL }}
      
      # 什么值得买签到配置
      smzdm_sk: ${{ secrets.SMZDM_SK }}
      smzdm_token: ${{ secrets.SMZDM_TOKEN }}
      smzdm_cookie: ${{ secrets.SMZDM_COOKIE }}
      
      # 52破解签到配置
      pojie_cookie: ${{ secrets.POJIE_COOKIE }}
      
      # 阿里云盘签到配置
      aliyundrive_refresh_token: ${{ secrets.ALIYUNDRIVE_REFRESH_TOKEN }}
      
      # NatPierce签到配置
      natpierce_username: ${{ secrets.NATPIERCE_USERNAME }}
      natpierce_password: ${{ secrets.NATPIERCE_PASSWORD }}
      
      # V2EX签到配置
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}
      
      # LeanCloud配置
      lc_app_id: ${{ secrets.LC_APP_ID }}
      lc_app_key: ${{ secrets.LC_APP_KEY }}
      
      # 华为云API配置
      ak: ${{ secrets.HW_ACCESS_KEY }}
      sk: ${{ secrets.HW_SECRET_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: deploy compress zip function file to huaweicloud functiongraph
        uses: Buronn/huaweicloud-functiongraph-action@v0.1.0
        with:
          access_key_id: ${{ secrets.ACCESSKEY }}
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: 'cn-north-4'
          func_name: ${{ secrets.FUNCTIONNAME }}
          runtime: 'Python3.6'
          timeout: 60
          memory_size: 128
          code_type: 'zip'
          code_path: 'sfc'
          #code_filename: 'sfc.zip'
          handler: 'index.handler'