name: Deploy-Functiongraph

on:
  push:
    branches: 
    - 'main'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2
     
    - name: compress function files or director to zip file
      run: zip -r -j sfc.zip ./sfc/

    - name: deploy compress zip function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0.4

      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: https://functiongraph.cn-north-4.myhuaweicloud.com
        project_id: ${{ secrets.PROJECT_ID }}
        function_codetype: zip
        function_urn: urn:fss:cn-north-4:${{ secrets.PROJECT_ID }}:function:default:${{ secrets.FUNCTIONNAME }}:latest
        function_file: ./sfc.zip
